CURRENT_TAKER_FEE_RATE = 0.0025
CURRENT_MAKER_FEE_RATE = 0.0015

M_FEE_ONE = 1 - CURRENT_MAKER_FEE_RATE
M_FEE_TWO = M_FEE_ONE ** 2
M_FEE_THREE = M_FEE_ONE ** 3

M_INV_FEE_ONE = 1.0 / M_FEE_ONE
M_INV_FEE_TWO = 1.0 / M_FEE_TWO
M_INV_FEE_THREE = 1.0 / M_FEE_THREE

T_FEE_ONE = 1 - CURRENT_TAKER_FEE_RATE
T_FEE_TWO = T_FEE_ONE ** 2
T_FEE_THREE = T_FEE_ONE ** 3

T_INV_FEE_ONE = 1.0 / T_FEE_ONE
T_INV_FEE_TWO = 1.0 / T_FEE_TWO
T_INV_FEE_THREE = 1.0 / T_FEE_THREE

MINIMUM_LENDING_AMOUNT = 0.001
MINIMUM_LENDING_RATE = 0.000001

BTC_X_USDT_PAIRS = [
	['BTC_ETH', 'USDT_ETH'],
	['BTC_XMR', 'USDT_XMR'],
	['BTC_DASH', 'USDT_DASH'],
	['BTC_LTC', 'USDT_LTC'],
	['BTC_NXT', 'USDT_NXT'],
	['BTC_XRP', 'USDT_XRP'],
]

BTC_X_XMR_PAIRS = [
	['BTC_LTC', 'XMR_LTC'],
	['BTC_MAID', 'XMR_MAID'],
	['BTC_QORA', 'XMR_QORA'],
	['BTC_NXT', 'XMR_NXT'],
	['BTC_DASH', 'XMR_DASH'],
	['BTC_XDN', 'XMR_XDM'],
	['BTC_DIEM', 'XMR_DIEM'],
]

LOAN_CURRENCIES = ['BTC', 'BTS', 'CLAM', 'DASH', 'DOGE', 'ETH', 'FCT', 'LTC', 'MAID', 'STR', 'XMR', 'XRP',]
